# Generated by Django 4.1 on 2022-09-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_alter_ninja_dojo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
